shopify:
  outputs:
    dev:
      dataset: staging
      job_execution_timeout_seconds: 540
      job_retries: 1
      location: EU
      method: oauth
      impersonate-service-account: 1096673245843-compute@developer.gserviceaccount.com
      priority: interactive
      project: impression-digital
      threads: 1
      type: bigquery

  target: dev